/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  // pieces: [{type: 'autogenerated', dirName: 'apidocs'}],

  // But you can create a sidebar manually

  api: [
    // "apidocs/overview",
    // "apidocs/faq",

    // {
    //   type: 'category',
    //   label: 'Overview',
    //   items: ['apidocs/overview'],
    //   collapsible: true
    // },
    {
      // type: "doc",
      // id: "apidocs/use-cases",
      // label: "Use cases",
      // collapsible: false
    },
    {
      type: 'category',
      label: 'API',
      items: ['API/overview', 'API/use-cases', 'API/faq', 'API/test'],
      collapsible: true
    },
  ],
}; 

export default sidebars;
